// ============================================================
// SEED DATA — Base de datos de prueba
// Datos realistas para simular el flujo completo de la app
// ============================================================

import type { User, Business, Product, GeneratedContent, Conversation, Metric } from "@/types"

export const SEED_USERS: User[] = [
  {
    id: "user_001",
    name: "María González",
    email: "maria@brownies.co",
    role: "owner",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
  },
  {
    id: "user_002",
    name: "Andrés Torres",
    email: "andres@ropaurbanakld.co",
    role: "owner",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 15,
  },
  {
    id: "user_003",
    name: "Catalina Ruiz",
    email: "cata@accesorios.co",
    role: "owner",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
  },
]

export const SEED_BUSINESSES: Business[] = [
  {
    id: "biz_001",
    userId: "user_001",
    name: "Brownies de María",
    description: "Repostería artesanal hecha con amor y los mejores ingredientes. Brownies, cupcakes y tortas para todos los momentos especiales. Pedidos todos los días.",
    category: "comida",
    logo: "🍫",
    theme: "artesanal",
    telegram: "browniesdemaria",
    whatsapp: "573001234567",
    tone: "amigable",
    slug: "brownies-de-maria",
    isPublic: true,
    colors: { primary: "#5d4037", secondary: "#795548", accent: "#ff8f00" },
    enfoque: "Repostería artesanal tradicional con foco en brownies y cupcakes caseros.",
    aspiraciones: "Montar una pastelería física propia y ofrecer talleres presenciales de repostería.",
    necesidades: "Capital semilla para comprar un horno industrial, registrar la marca y capacitación en costos.",
    onboardingStep: 4,
    growthRoute: {
      identityId: "I02",
      identityName: "Mujer emprendedora",
      stage: "inicio",
      recommendedEntities: ["E01", "E04", "E05"],
      customAdvice: "María, tu dedicación en la repostería artesanal es admirable. Dado tu perfil y necesidades, te sugerimos iniciar con el **Fondo Mujer Libre y Productiva** (E04), el cual ofrece financiamiento y asesoría integral para mitigar las barreras de crédito típicas de emprendedoras. Adicionalmente, el **SENA - Fondo Emprender** (E01) es clave para postular tu plan de negocio y obtener capital semilla para el horno industrial. Tu primer paso concreto en la Cámara de Comercio (E05) debe ser obtener tu RUT y matricular tu marca.",
      createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
      isActive: true,
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
  },
  {
    id: "biz_002",
    userId: "user_002",
    name: "Ropa Urbana KLD",
    description: "Ropa urbana, streetwear y accesorios para jóvenes con estilo. Envíos a todo el país. IG: @ropaurbanakld",
    category: "ropa",
    logo: "👕",
    theme: "callejero",
    telegram: "ropaurbanakld",
    whatsapp: "573009876543",
    tone: "divertido",
    slug: "ropa-urbana-kld",
    isPublic: true,
    colors: { primary: "#212121", secondary: "#424242", accent: "#ffeb3b" },
    enfoque: "Moda streetwear y ropa oversize unisex para jóvenes con estilo urbano.",
    aspiraciones: "Ser una marca reconocida a nivel nacional e iniciar envíos internacionales.",
    necesidades: "Estrategias avanzadas de marketing digital, contacto con proveedores de tela de gran escala, y alianzas con influencers.",
    onboardingStep: 4,
    growthRoute: {
      identityId: "I01",
      identityName: "Joven emprendedor",
      stage: "crecimiento",
      recommendedEntities: ["E02", "E06"],
      customAdvice: "Andrés, Ropa Urbana KLD tiene un fuerte arraigo digital. Para tu aspiración de internacionalización, **ProColombia** (E06) es la entidad ideal para formarte en exportación de confecciones. Asimismo, **iNNpulsa** (E02) ofrece programas de escalamiento comercial y redes de contacto que te conectarán con proveedores mayoristas de textil y aceleradoras de comercio electrónico.",
      createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
      isActive: true,
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 15,
  },
  {
    id: "biz_003",
    userId: "user_003",
    name: "Accesorios Cata",
    description: "Bisutería y accesorios únicos hechos a mano. Cada pieza es irrepetible. Envíos a toda Colombia.",
    category: "artesanias",
    logo: "💎",
    theme: "premium",
    telegram: "accesorios_cata",
    whatsapp: "573115556789",
    tone: "elegante",
    slug: "accesorios-cata",
    isPublic: true,
    colors: { primary: "#1a1a1a", secondary: "#2d2d2d", accent: "#c9a84c" },
    enfoque: "Bisutería fina y accesorios elaborados a mano utilizando perlas de río y baño de oro.",
    aspiraciones: "Crear un catálogo premium de alta joyería y formalizar el RUT de la empresa.",
    necesidades: "Asesoría para formalización legal (obtener RUT), diseño de empaques de lujo y finanzas básicas para emprendedores.",
    onboardingStep: 4,
    growthRoute: {
      identityId: "I03",
      identityName: "Negocio informal",
      stage: "formalización",
      recommendedEntities: ["E03", "E05", "E07"],
      customAdvice: "Catalina, tus piezas artesanales tienen un alto valor percibido. Te recomendamos iniciar la ruta de formalización con la **Cámara de Comercio** (E05) para obtener tu RUT y formalizar la matrícula mercantil, lo cual desbloqueará el acceso a las líneas de crédito preferenciales para microempresarios que ofrece **Bancóldex** (E03). Adicionalmente, apóyate en los programas de transformación digital de **MinTIC** (E07) para potenciar tu presencia de catálogo en canales premium.",
      createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
      isActive: true,
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
  },
]

export const SEED_PRODUCTS: Product[] = [
  // --- Brownies de María ---
  {
    id: "prod_001",
    businessId: "biz_001",
    name: "Brownies de Chocolate Belga",
    description: "Recién horneados cada mañana con chocolate belga premium. Suaves por dentro, crujientes por fuera.",
    price: 15000,
    stock: 20,
    images: ["🍫"],
    category: "Repostería",
    isActive: true,
    aiGenerated: {
      name: "Brownies de Chocolate Belga Premium",
      description: "Irresistibles brownies artesanales elaborados con el mejor chocolate belga 70% cacao. Cada mordisco es una explosión de sabor.",
      copy: "El antojo que no puedes resistir. Recién horneados, listos para ti. 🍫",
      hashtags: ["#Brownies", "#ChocolateBelga", "#Artesanal", "#Repostería", "#AntojosDulces"],
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 25,
  },
  {
    id: "prod_002",
    businessId: "biz_001",
    name: "Cupcakes Personalizados",
    description: "Perfectos para cumpleaños y eventos especiales. Elige el sabor y la decoración.",
    price: 5000,
    stock: 30,
    images: ["🧁"],
    category: "Repostería",
    isActive: true,
    aiGenerated: {
      name: "Cupcakes Artesanales Personalizados",
      description: "Cupcakes únicos diseñados especialmente para ti. Disponibles en sabores de vainilla, chocolate y red velvet con decoración personalizada.",
      copy: "Haz tu evento inolvidable con cupcakes únicos. ¡Cada uno cuenta tu historia! 🧁✨",
      hashtags: ["#Cupcakes", "#Personalizado", "#Cumpleaños", "#Repostería", "#Artesanal"],
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 20,
  },
  {
    id: "prod_003",
    businessId: "biz_001",
    name: "Torta de 3 Leches",
    description: "Tradicional y esponjosa. Solo disponible los fines de semana. Pedido con 24h de anticipación.",
    price: 45000,
    stock: 5,
    images: ["🎂"],
    category: "Tortas",
    isActive: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 18,
  },
  {
    id: "prod_004",
    businessId: "biz_001",
    name: "Café Artesanal Premium",
    description: "Tostado suave de origen colombiano 100%. Perfecto para acompañar tus brownies.",
    price: 8000,
    stock: 50,
    images: ["☕"],
    category: "Bebidas",
    isActive: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
  },
  {
    id: "prod_005",
    businessId: "biz_001",
    name: "Caja Sorpresa Repostera",
    description: "Combinación sorpresa de nuestros mejores productos. Ideal para regalar.",
    price: 35000,
    stock: 0,
    images: ["🎁"],
    category: "Combos",
    isActive: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },

  // --- Ropa Urbana KLD ---
  {
    id: "prod_006",
    businessId: "biz_002",
    name: "Hoodie Oversize KLD Classic",
    description: "Hoodie oversize unisex. Algodón premium 320g. Tallas S-XXL. Colores: negro, blanco, gris.",
    price: 85000,
    stock: 45,
    images: ["👕"],
    category: "Hoodies",
    isActive: true,
    aiGenerated: {
      name: "Hoodie Oversize KLD Classic Edition",
      description: "El hoodie que define tu estilo. Fabricado en algodón premium 320g con corte oversize perfecto. Disponible en negro, blanco y gris.",
      copy: "Viste el street, siente el premium. KLD Classic nunca falla. 🔥",
      hashtags: ["#Streetwear", "#Hoodie", "#Oversize", "#KLD", "#RopaUrbana"],
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 12,
  },
  {
    id: "prod_007",
    businessId: "biz_002",
    name: "Jogger Cargo Urbano",
    description: "Pantalón cargo con múltiples bolsillos. Material: algodón ripstop. Disponible en negro y kaki.",
    price: 75000,
    stock: 28,
    images: ["👖"],
    category: "Pantalones",
    isActive: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 8,
  },

  // --- Accesorios Cata ---
  {
    id: "prod_008",
    businessId: "biz_003",
    name: "Collar de Perlas Naturales",
    description: "Collar artesanal con perlas naturales de río. Cierre de plata 925. Longitud ajustable.",
    price: 120000,
    stock: 8,
    images: ["📿"],
    category: "Collares",
    isActive: true,
    aiGenerated: {
      name: "Collar Elegance — Perlas Naturales de Río",
      description: "Delicado collar artesanal elaborado con perlas naturales de río seleccionadas a mano. Cierre de plata 925 con longitud ajustable para máxima versatilidad.",
      copy: "La elegancia no se busca, se lleva. ✨",
      hashtags: ["#Collares", "#PerlasNaturales", "#Artesanal", "#Bisutería", "#Handmade"],
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
  },
  {
    id: "prod_009",
    businessId: "biz_003",
    name: "Aretes Hoja Dorada",
    description: "Aretes en forma de hoja bañados en oro 18k. Ligeros y resistentes. Antialérgicos.",
    price: 65000,
    stock: 15,
    images: ["✨"],
    category: "Aretes",
    isActive: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },
]

export const SEED_GENERATED_CONTENT: GeneratedContent[] = [
  {
    id: "content_001",
    businessId: "biz_001",
    type: "marketing_post",
    prompt: "Generar post de Instagram para brownies artesanales, objetivo: lanzamiento",
    response: "🍫 Brownies recién horneados con el equilibrio perfecto entre suavidad y chocolate intenso.\n\n🔥 Promoción de lanzamiento:\nCompra 2 paquetes y recibe envío gratis este fin de semana.\n\n¡Pide el tuyo ahora! 👇\n\n#Brownies #Chocolate #Artesanal #Repostería #AntojosDulces",
    provider: "groq",
    createdAt: Date.now() - 1000 * 60 * 60 * 2,
  },
  {
    id: "content_002",
    businessId: "biz_001",
    type: "slogan",
    prompt: "Slogan para negocio de repostería artesanal",
    response: "\"El dulce que te abraza por dentro\" 🍫",
    provider: "groq",
    createdAt: Date.now() - 1000 * 60 * 60 * 24,
  },
  {
    id: "content_003",
    businessId: "biz_001",
    type: "campaign",
    prompt: "Campaña completa para cupcakes personalizados, objetivo: promoción",
    response: "🎉 ¡SEMANA DE CUPCAKES PERSONALIZADOS!\n\nEste miércoles y jueves:\n✅ Pide 6 cupcakes y recibe 1 gratis\n✅ Personalización de decoración sin costo adicional\n✅ Entrega el mismo día en Bogotá norte\n\n📞 Escríbenos YA y asegura tu pedido\n⚠️ Disponibilidad limitada",
    provider: "groq",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: "content_004",
    businessId: "biz_002",
    type: "marketing_post",
    prompt: "Post para hoodie oversize, objetivo: urgencia por stock limitado",
    response: "⚠️ ÚLTIMAS UNIDADES — Hoodie KLD Classic\n\nNegro talla L: solo quedan 3️⃣\nBlanco talla M: solo quedan 2️⃣\n\n🔥 Precio especial esta semana: $85.000\n💳 Pagos con Nequi y Bancolombia\n📦 Envío a todo el país en 2-3 días\n\n¡No te quedes sin el tuyo! 👇\n\n#Streetwear #Hoodie #KLD #RopaUrbana #Moda",
    provider: "groq",
    createdAt: Date.now() - 1000 * 60 * 60 * 5,
  },
]

export const SEED_CONVERSATIONS: Conversation[] = [
  {
    id: "conv_001",
    businessId: "biz_001",
    platform: "telegram",
    customerName: "Carlos M.",
    messages: [
      { role: "user", content: "Hola, ¿tienen brownies disponibles para hoy?", timestamp: Date.now() - 1000 * 60 * 30 },
      { role: "assistant", content: "¡Hola Carlos! 😊 Sí, tenemos brownies disponibles. ¿Cuántos necesitas y a qué hora los necesitas?", timestamp: Date.now() - 1000 * 60 * 29 },
      { role: "user", content: "Necesito una caja de 6 para las 5pm", timestamp: Date.now() - 1000 * 60 * 25 },
      { role: "assistant", content: "¡Perfecto! Una caja de 6 brownies de chocolate belga son $15.000. ¿Los recoge en nuestro punto o necesita domicilio?", timestamp: Date.now() - 1000 * 60 * 24 },
    ],
    createdAt: Date.now() - 1000 * 60 * 30,
  },
  {
    id: "conv_002",
    businessId: "biz_001",
    platform: "telegram",
    customerName: "Valentina R.",
    messages: [
      { role: "user", content: "¿Hacen tortas personalizadas para cumpleaños?", timestamp: Date.now() - 1000 * 60 * 60 * 3 },
      { role: "assistant", content: "¡Claro que sí! 🎂 Hacemos tortas completamente personalizadas. ¿Para cuándo la necesitas y cuántas personas?", timestamp: Date.now() - 1000 * 60 * 60 * 3 + 30000 },
      { role: "user", content: "Para el sábado, somos 15 personas", timestamp: Date.now() - 1000 * 60 * 60 * 2 },
      { role: "assistant", content: "Para 15 personas te recomendamos la torta de 3 leches de 30cm. El precio es $65.000. Necesitamos el pedido con mínimo 48 horas de anticipación. ¿Te parece bien?", timestamp: Date.now() - 1000 * 60 * 60 * 2 + 30000 },
    ],
    createdAt: Date.now() - 1000 * 60 * 60 * 3,
  },
  {
    id: "conv_003",
    businessId: "biz_002",
    platform: "telegram",
    customerName: "Diego F.",
    messages: [
      { role: "user", content: "¿El hoodie negro talla L está disponible?", timestamp: Date.now() - 1000 * 60 * 15 },
      { role: "assistant", content: "¡Hola! 🔥 Sí, tenemos el hoodie negro talla L disponible. Son $85.000 con envío a todo el país. ¿Te lo enviamos?", timestamp: Date.now() - 1000 * 60 * 14 },
    ],
    createdAt: Date.now() - 1000 * 60 * 15,
  },
]

export const SEED_METRICS: Metric[] = [
  {
    businessId: "biz_001",
    productViews: {
      prod_001: 142,
      prod_002: 67,
      prod_003: 41,
      prod_004: 98,
    },
    productQueries: {
      prod_001: 34,
      prod_002: 28,
      prod_003: 15,
      prod_004: 12,
    },
    totalMessages: 67,
    contentGenerated: 24,
    period: "week",
  },
  {
    businessId: "biz_002",
    productViews: { prod_006: 89, prod_007: 54 },
    productQueries: { prod_006: 22, prod_007: 18 },
    totalMessages: 31,
    contentGenerated: 8,
    period: "week",
  },
]
